### ISSUE TITLE
Getting TypeError: Cannot read property 'clientHeight' of undefined

### ISSUE THREAD

**Issue by oiojin831** [drcmda/react-springy-parallax#5] opened 2017-04-10 16:08 UTC
Hello!
I am getting
```TypeError: Cannot read property 'clientHeight' of undefined```
this error when I try to go to other route using [zeit/next](https://github.com/zeit/next.js).
any hint how to fix this?
Thanks.

**Comment by drcmda** [comment] 2017-04-10 21:00
@oiojin831 Is this something specific about your routes or z/next? I need more data or a real example for this. No idea what would cause it, clientHeight gets called in Parallax.update, which fetches container from this.refs. If it doesn't find the container, something's going on ...

**Comment by storybynumbers** [comment] 2017-04-25 12:12
I also came across this while navigating to another page. I don't believe the issue is related to the router. It's a case where both the `Layer` and `Parallax` components are unmounted at the same time.

The error reported by @oiojin831 occurs when `<Layer>` is unmounted, requests an `update()` on the `<Parallax>` container, but the container DOM element no longer exists.

It would appear parents are unmounted before their children, which surprises me.

**Comment by drcmda** [comment] 2017-04-26 21:27
@oiojin831 @storybynumbers Very strange. I have never worked with next, is that specific to it?

Merged your PR and added conditions in Layer just to be sure. Published to npm as well. Thanks for debugging it!

**Comment by storybynumbers** [comment] 2017-05-04 07:10
Sorry for the late reaction @drcmda ! The new version is working, I've tested it locally. Thanks! :)

**Closed as completed** 2017-05-09 15:24 UTC
